### ISSUE TITLE
ignore punctuation in element names and attribute values

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/llt-segmenter#11]
the segmenter should ignore punctuation in element names and attribute values.

**Comment by LFDM** [comment]
Not a bug one should be proud of :) Will fix tomorrow morning.

**Comment by LFDM** [comment]
Just to be safe, I am going to add one more spec to 'llt' before I close this.

**Comment by LFDM** [comment]
Ok, should be good, cf. latin-language-toolkit/llt@e3234ce
